{{- if .Values.networkPolicies.enabled }}
# Needed for access to secrets at startup
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-apiserver-egress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: {{ .Values.networkPolicies.defaultSelectorKey }}
        operator: In
        values:
        {{- range .Values.networkPolicies.defaultSelectorValues }}
          - {{ . }}
        {{- end }}
  policyTypes:
  - Egress
  egress:
    - to:
      - ipBlock:
          cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
          {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
          # ONLY Block requests to cloud metadata IP
          except:
            - 169.254.169.254/32
          {{- end }}
{{- end }}
