{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-in-ns-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: {{ .Values.networkPolicies.defaultSelectorKey }}
        operator: In
        values:
        {{- range .Values.networkPolicies.defaultSelectorValues }}
          - {{ . }}
        {{- end }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
{{- end }}
