{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alloy-receiver-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: {{ .Values.networkPolicies.defaultSelectorKey }}
        operator: In
        values:
        {{- range .Values.networkPolicies.defaultSelectorValues }}
          - {{ . }}
        {{- end }}
  policyTypes:
  - Ingress
  ingress:
  # Since OTLP traffic can and should come from anywhere,
  # we don't want to restrict the source.
  - ports:
    {{- range (index .Values "k8s-monitoring" "alloy-receiver" "alloy" "extraPorts" ) }}
    - port: {{ .port }}
    {{- end }}    
{{- end }}

