{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alloy-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: {{ .Values.networkPolicies.defaultSelectorKey }}
        operator: In
        values:
        {{- range .Values.networkPolicies.defaultSelectorValues }}
          - {{ . }}
        {{- end }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - key: {{ .Values.networkPolicies.defaultSelectorKey }}
            operator: In
            values:
            {{- range .Values.networkPolicies.defaultSelectorValues }}
              - {{ . }}
            {{- end }}
  egress:
  - to:
    - podSelector:
        matchExpressions:
          - key: {{ .Values.networkPolicies.defaultSelectorKey }}
            operator: In
            values:
            {{- range .Values.networkPolicies.defaultSelectorValues }}
              - {{ . }}
            {{- end }}
{{- end }}