{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alloy-sidecar-scraping
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: {{ .Values.networkPolicies.defaultSelectorKey }}
        operator: In
        values:
        {{- range .Values.networkPolicies.defaultSelectorValues }}
          - {{ . }}
        {{- end }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus 
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 15020
      protocol: TCP
{{- end }}
