{{- if and .Values.networkPolicies.enabled (not .Values.monitoring.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-lookups
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: alloy
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: TCP
    - port: 5353
      protocol: UDP
    {{- end }}
{{- end }}
